"""Assemble a PSS operation model into one SystemVerilog package.

Built as a class, for the reasons `c/backend.py` and `py/backend.py` are:

* **Every `emit_*` returns text; only `generate` touches disk.** A method that
  writes cannot be wrapped by a subclass calling `super()`.
* **The package is exactly its `package_sections()`**, in order, each section
  carrying its own trailing blank -- so a subclass changes one by name
  (`targets/sections.py`) rather than by re-deriving the whole file.

SV has no forward references inside a package, so the section ORDER is part of
the output being correct, not a matter of taste: the import and context
interfaces, then the component base that holds the import API, then one class
per component type -- each base before what extends it, each child before what
contains it -- then the factory that builds the tree.

Like `PyOpModelBackend`, this carries no `@overridable` marks and is NOT a
published surface.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from ..sections import Section
from .lower_api_types import lower_api_types
from .lower_progseq import (emit_component_base, emit_component_class,
                            emit_context_api, emit_factory, emit_import_api,
                            emit_package_functions)
from .lower_reg_model import lower_register_model
from .reg_field_names import FieldNamer


class SvOpModelBackend(object):
    """Turns an `OpModel` into the text of one SystemVerilog package."""

    def __init__(self, pkg_name: str = "", reg_fields: str = "named"):
        #: The package name. Empty means `<root>_pkg`.
        self.pkg_name = pkg_name
        #: `named` or `folded` -- `--sv-reg-fields`. Spelling only: both
        #: generate the same bus traffic (see `progseq_gen.generate`).
        self.reg_fields = reg_fields

    # -- naming --------------------------------------------------------------

    def package_name(self, model) -> str:
        return self.pkg_name or f"{model.tree.name}_pkg"

    def file_name(self, model) -> str:
        return self.package_name(model) + ".sv"

    # -- assembly ------------------------------------------------------------

    def package_sections(self, model) -> List[Section]:
        """The package, in order. `emit_package` joins exactly these."""
        return [
            Section("banner", self.emit_banner),
            Section("package_open", self.emit_package_open),
            Section("reg_model", self.emit_reg_model),
            Section("api_types", self.emit_api_types),
            Section("functions", self.emit_functions),
            Section("import_api", self.emit_import_api),
            Section("context_api", self.emit_context_api),
            Section("component_base", self.emit_component_base),
            Section("components", self.emit_components),
            Section("factory", self.emit_factory),
            Section("package_close", self.emit_package_close),
        ]

    def emit_package(self, model) -> str:
        """The whole package: its sections' lines, in order."""
        lines: List[str] = []
        for _, emit in self.package_sections(model):
            lines += emit(model)
        return "\n".join(lines)

    def sections(self, model) -> Dict[str, str]:
        """`{"<file>:<section>": text}`. Nothing is written."""
        name = self.file_name(model)
        return {f"{name}:{s.name}": "\n".join(s.emit(model))
                for s in self.package_sections(model)}

    # -- shared --------------------------------------------------------------

    def namer(self, model, comp):
        """The field namer for ``comp``'s bodies, or None under `folded`.

        One per component: receiver paths resolve against that component's own
        fields. None disables the rewrite.
        """
        if self.reg_fields != "named":
            return None
        type_map = getattr(model.ctx, "type_map", {}) or {}
        return FieldNamer(comp, type_map)

    # -- sections ------------------------------------------------------------

    def emit_banner(self, model) -> List[str]:
        return ["// Generated by pssc (sv-progseq) -- do not edit.",
                f"// Root component: {model.tree.name}",
                ""]

    def emit_package_open(self, model) -> List[str]:
        return [f"package {self.package_name(model)};",
                "  import pssc_reg_pkg::*;",
                ""]

    def emit_reg_model(self, model) -> List[str]:
        """Register value structs and group classes, for the whole tree.

        The whole tree, not the root's own fields: a per-channel bank is reached
        through its channel component, so lowering only the root's registers
        emitted an empty file for any model that puts registers where the
        operations that use them are.
        """
        body, _, _ = lower_register_model(model.comp_dtypes)
        return [body]

    def emit_api_types(self, model) -> List[str]:
        text = lower_api_types(model.comp_dtypes, model.value_structs,
                               model.ctor_names,
                               [fn for e in model.entries for fn in e.functions]
                               + list(model.functions))
        return [text] if text else []

    def emit_functions(self, model) -> List[str]:
        """The package-scope functions the model calls, before the classes
        that call them."""
        if not model.functions:
            return []
        return ["  // ----- Package functions -----",
                emit_package_functions(model.functions, model.ctx,
                                       model.ctor_names),
                ""]

    def emit_import_api(self, model) -> List[str]:
        return ["  // ----- Import API: what the platform supplies -----",
                emit_import_api(model.root, model.ctor_names, model.ctx),
                ""]

    def emit_context_api(self, model) -> List[str]:
        """What the platform can call: the root's exported functions and the
        exported actions (design D9, D11, D12)."""
        return ["  // ----- Context API: what the platform calls -----",
                emit_context_api(model.root, model.exports, model.entries),
                ""]

    def emit_component_base(self, model) -> List[str]:
        """The class every component class extends (design D8)."""
        return [f"  // ----- Component base: {model.tree.name} -----",
                emit_component_base(model.root),
                ""]

    def emit_components(self, model) -> List[str]:
        """One class per component type (`model.classes`): each base before
        what derives from it, each child before what contains it, the root
        last."""
        lines: List[str] = []
        for comp in model.classes:
            lines.append(f"  // ----- Component: {comp.name} -----")
            lines.append(emit_component_class(model, comp,
                                              self.namer(model, comp)))
            lines.append("")
        return lines

    def emit_factory(self, model) -> List[str]:
        return [f"  // ----- Factory and root context: {model.tree.name} -----",
                emit_factory(model),
                ""]

    def emit_package_close(self, model) -> List[str]:
        return ["endpackage", ""]

    # -- disk ----------------------------------------------------------------

    def generate(self, model) -> List[Path]:
        """Write the package. The ONE method here that touches disk."""
        model.out_dir.mkdir(parents=True, exist_ok=True)
        path = model.out_dir / self.file_name(model)
        path.write_text(self.emit_package(model))
        return [path]
